### Introduction to Machine Learning @ NCCU.EDU.TW
##### prepared by Chao-Lin Liu

In [1]:
list1 = [1, 2, 3]
list2 = [2, 3, 4]

In [2]:
list3 = list1-list2 # 錯誤示範；一般的 python list 沒有這樣的功能

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [3]:
import numpy as np

### 兩個簡單的向量
#### $v1 = (1,2,3)$ 和 $v2=(4,5,6)$
### 以位置配對相減：$v3 = v2-v1 = (3,3,3)$
### 以位置配對相乘 (向量內積)：$v4 = v1*v2 = (4, 10, 18)$


In [4]:
v1 = np.array([1, 2, 3])

In [5]:
v2 = np.array([4,5,6])

In [6]:
v3 = v2 - v1

In [7]:
v3

array([3, 3, 3])

In [8]:
print(sum(v3))

9


In [9]:
v4=v1*v2

In [10]:
v4

array([ 4, 10, 18])

In [11]:
v11 = np.array([1,2,3,4,5])
v22 = np.array([6,7,8,9,0])

In [12]:
v11 * v22

array([ 6, 14, 24, 36,  0])

In [13]:
# 透過函數更加厲害一些
def cool (v1, v2):
    return v1*v2

In [14]:
# 你覺得 v33 會是甚麼？
v33 = cool(v11, v22)

In [15]:
v33

array([ 6, 14, 24, 36,  0])

In [16]:
# cool 並不知道將來收到的向量的長度，可以為任意長度的向量服務
v33

array([ 6, 14, 24, 36,  0])

In [17]:
v1

array([1, 2, 3])

In [18]:
# 向量加上單一數值 (scalar) 也可以
v4 = v1 + 1

In [19]:
v4

array([2, 3, 4])

In [20]:
# 矩陣更加有用
m1 = np.array([[1,2,3],[4,5,6]])

In [21]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
m1.shape

(2, 3)

In [23]:
m2 = np.array([[1,2],[3,4],[5,6]])

$m1 = \begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\end{bmatrix}$
$m2 = \begin{bmatrix}1 & 2\\3 & 4\\5  & 6\end{bmatrix}$

In [24]:
m2.shape

(3, 2)

In [25]:
m1*m2 # 錯誤示範

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [26]:
# 學會一個新的指令
np.dot(m1,m2)

array([[22, 28],
       [49, 64]])

In [27]:
# 轉置矩陣 (transpose)
m3 = m1.T

In [28]:
m3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
# 把矩陣丟給函數也有 broadcasting 的效果
woo = np.sin(m3)

In [30]:
woo

array([[ 0.84147098, -0.7568025 ],
       [ 0.90929743, -0.95892427],
       [ 0.14112001, -0.2794155 ]])

In [31]:
#有一些時候，你可能想要改變矩陣的資料的配置：reshape
import numpy as np
v5 = np.array([1,2,3,4,5,6])

In [32]:
v5

array([1, 2, 3, 4, 5, 6])

In [33]:
v6=v5.reshape(3,2)

In [34]:
v6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
v7 = v5.reshape(2,3)

In [36]:
v7

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
sum(v7)

array([5, 7, 9])

In [38]:
sum(np.array([1,2,3,4,5,6]))

21